### ISSUE TITLE
Package collapse

### ISSUE THREAD

**Issue by nantofu** [Kelin-Hong/CalendarListView#1]
今天下载了你的安装包，但是程序没有启动成功，直接崩溃了。
崩溃日志如下:
[crash log.txt](https://github.com/Kelin-Hong/CalendarListView/files/421595/crash.log.txt)
机型：华为荣耀 3X
SDK Version：4.4.2

**Comment by daiji168** [comment]
apk可以安装，运行直接崩溃；
SDK：4.4.2
机型：三星

**Comment by Kelin-Hong** [comment]
sample 用了fresco的原因，部分机型的处理器不支持，已经替换成picasso，try again！
